[general]
live_config_reload = true

import = [
  "~/.config/alacritty/themes/mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[scrolling]
history = 10000

[window]
decorations = "buttonless"
dynamic_padding = false

[window.padding]
x = 8
y = 8

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[[keyboard.bindings]]
chars = "\u0002\u0022"
key = "N"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002%"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u00020"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002o"
key = "O"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002z"
key = "Z"
mods = "Control"

# see: https://stackoverflow.com/a/78008190
[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"
